from CallCreditSpread import callCreditSpread
from PutCreditSpread import putCreditSpread
from CallDebitSpread import callDebitSpread
from PutDebitSpread import putDebitSpread
from ShortPut import shortPut
from ShortCall import shortCall
from LongPut import longPut
from LongCall import longCall
from CoveredCall import coveredCall
from IronCondor import ironCondor
from ShortStrangle import shortStrangle